export enum GetByOriginTypes {
  REQUEST = "STORE__GET_BY_ORIGIN__REQUEST",
  SUCCESS = "STORE__GET_BY_ORIGIN__SUCCESS",
  FAILURE = "STORE__GET_BY_ORIGIN__FAILURE",
}

export enum UpdateTypes {
  REQUEST = "STORE__UPDATE__REQUEST",
  SUCCESS = "STORE__UPDATE__SUCCESS",
  FAILURE = "STORE__UPDATE__FAILURE",
}
