export enum GetTypes {
  REQUEST = "SETTINGS__GET__REQUEST",
  SUCCESS = "SETTINGS__GET__SUCCESS",
  FAILURE = "SETTINGS__GET__FAILURE",
}

export enum UpdateTypes {
  REQUEST = "SETTINGS__UPDATE__REQUEST",
  SUCCESS = "SETTINGS__UPDATE__SUCCESS",
  FAILURE = "SETTINGS__UPDATE__FAILURE",
}
